import { useEffect, useState } from "react";
import Head from "next/head";
import Container from "@/components/Container";
import TransactionTableHeaderSearchBox from "@/components/Transaction/Table/HeaderSearchBox";
import TransactionTablePaidAt from "@/components/Transaction/Table/PaidAt";
import TransactionTablePaymentStatus from "@/components/Transaction/Table/PaymentStatus";
import TransactionTableTrackId from "@/components/Transaction/Table/TrackId";
import { Table, TableProps, Typography } from "antd";
import PriceHelper from "@/helpers/price";
import textHelper from "@/helpers/text";
import TransactionService from "@/services/transaction";
import type { Transaction } from "@/types/transaction";
import type { Nullable } from "ts-wiz";

let timeoutRef: Nullable<NodeJS.Timeout> = null;

const TransactionPage = () => {
  const [trackIdSearch, setTrackIdSearch] = useState<Nullable<Transaction["trackId"]>>(null);
  const [cardNumberSearch, setCardNumberSearch] = useState<Transaction["cardNumber"]>("");

  const [transactionData, setTransactionData] = useState<Array<Transaction>>([]);

  const handleGetTransactionData = async () => {
    const transactionData = await TransactionService.list({
      trackId: trackIdSearch,
      cardNumber: cardNumberSearch,
    });
    setTransactionData(transactionData);
  };

  const columns: TableProps<Transaction>["columns"] = [
    {
      title: (
        <TransactionTableHeaderSearchBox
          type="number"
          inputValue={trackIdSearch || ""}
          onInputChange={(e) => {
            const { value } = e.target;
            setTrackIdSearch(value ? Number(value) : null);
          }}
          onClear={() => setTrackIdSearch(null)}
          title="شماره تراکنش"
        />
      ),
      dataIndex: "trackId",
      key: "trackId",
      render: (data) => <TransactionTableTrackId trackId={data} />,
      width: 200,
    },
    {
      title: "وضعیت تراکنش",
      dataIndex: "status",
      key: "status",
      render: (data) => <TransactionTablePaymentStatus status={data} />,
    },
    {
      title: "تاریخ پرداخت",
      dataIndex: "paidAt",
      key: "paidAt",
      render: (data) => <TransactionTablePaidAt date={data} />,
    },
    {
      title: "مبلغ",
      dataIndex: "amount",
      key: "amount",
      render: (data) => (
        <Typography>{textHelper.toPersianDigits(PriceHelper.format(data, { unit: "ریال" }))}</Typography>
      ),
    },
    {
      title: (
        <TransactionTableHeaderSearchBox
          title="شماره کارت"
          type="string"
          inputValue={cardNumberSearch}
          onInputChange={(e) => setCardNumberSearch(e.target.value)}
          onClear={() => setCardNumberSearch("")}
        />
      ),
      dataIndex: "cardNumber",
      key: "cardNumber",
      width: 300,
      render: (data) => <Typography>{textHelper.toPersianDigits(data)}</Typography>,
    },
  ];

  useEffect(() => {
    timeoutRef = setTimeout(handleGetTransactionData, 500);
    return () => {
      if (timeoutRef) clearTimeout(timeoutRef);
    };
  }, [, trackIdSearch, cardNumberSearch]);

  return (
    <>
      <Head>
        <title>Zibal Technical Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Table style={{ width: "100%" }} columns={columns} dataSource={transactionData} pagination={false} />
      </Container>
    </>
  );
};

export default TransactionPage;
